"""add indexes

Revision ID: 38d370a98c6c
Revises: af18c7ef5fb3
Create Date: 2026-03-24 17:37:30.351333

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "38d370a98c6c"
down_revision: Union[str, Sequence[str], None] = "af18c7ef5fb3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_chats_chat_id"), "chats", type_="unique")
    op.create_index(op.f("ix_chats_chat_id"), "chats", ["chat_id"], unique=True)
    op.create_index(
        op.f("ix_link_chat_chat_id"), "link_chat", ["chat_id"], unique=False
    )
    op.create_index(
        op.f("ix_link_chat_link_id"), "link_chat", ["link_id"], unique=False
    )
    op.create_index(
        op.f("ix_link_tag_tag_name"), "link_tag", ["tag_name"], unique=False
    )
    op.drop_constraint(op.f("uq_links_url"), "links", type_="unique")
    op.create_index(op.f("ix_links_url"), "links", ["url"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_links_url"), table_name="links")
    op.create_unique_constraint(
        op.f("uq_links_url"), "links", ["url"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_link_tag_tag_name"), table_name="link_tag")
    op.drop_index(op.f("ix_link_chat_link_id"), table_name="link_chat")
    op.drop_index(op.f("ix_link_chat_chat_id"), table_name="link_chat")
    op.drop_index(op.f("ix_chats_chat_id"), table_name="chats")
    op.create_unique_constraint(
        op.f("uq_chats_chat_id"),
        "chats",
        ["chat_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
