"""add chat_id to link_tag and change FK

Revision ID: 7c3711e90450
Revises: 38d370a98c6c
Create Date: 2026-05-07 20:25:47.135885

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7c3711e90450"
down_revision: Union[str, Sequence[str], None] = "38d370a98c6c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("link_tag", sa.Column("chat_id", sa.BigInteger(), nullable=False))
    op.drop_constraint("pk_link_tag", "link_tag", type_="primary")
    op.create_primary_key("pk_link_tag", "link_tag", ["chat_id", "link_id", "tag_name"])
    op.drop_constraint(op.f("link_tag_link_id_fkey"), "link_tag", type_="foreignkey")
    op.create_foreign_key(
        None,
        "link_tag",
        "link_chat",
        ["chat_id", "link_id"],
        ["chat_id", "link_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "link_tag", type_="foreignkey")
    op.drop_constraint("pk_link_tag", "link_tag", type_="primary")
    op.drop_column("link_tag", "chat_id")
    op.create_foreign_key(
        op.f("link_tag_link_id_fkey"),
        "link_tag",
        "links",
        ["link_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.create_primary_key("pk_link_tag", "link_tag", ["link_id", "tag_name"])
    # ### end Alembic commands ###
