"""add updated_at to links

Revision ID: af18c7ef5fb3
Revises: 001
Create Date: 2026-03-24 17:29:52.825849

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "af18c7ef5fb3"
down_revision: Union[str, Sequence[str], None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("idx_chats_chat_id"), table_name="chats")
    op.drop_index(op.f("idx_link_chat_chat_id"), table_name="link_chat")
    op.drop_index(op.f("idx_link_chat_link_id"), table_name="link_chat")
    op.drop_index(op.f("idx_link_tag_link_id"), table_name="link_tag")
    op.add_column(
        "links", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_index(op.f("idx_links_url"), table_name="links")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("idx_links_url"), "links", ["url"], unique=False)
    op.drop_column("links", "updated_at")
    op.create_index(op.f("idx_link_tag_link_id"), "link_tag", ["link_id"], unique=False)
    op.create_index(
        op.f("idx_link_chat_link_id"), "link_chat", ["link_id"], unique=False
    )
    op.create_index(
        op.f("idx_link_chat_chat_id"), "link_chat", ["chat_id"], unique=False
    )
    op.create_index(op.f("idx_chats_chat_id"), "chats", ["chat_id"], unique=False)
    # ### end Alembic commands ###
